debug: false

# See: https://timezonedb.com/time-zones
ZoneId: 'Europe/Paris'
nopermission: '&cYou don''t have permission to use this command'
spacers: [' ', ', ', ' and ']
date:
  format:
    plural: ['years', 'months', 'days', 'hours', 'minutes', 'seconds']
    singular: ['year', 'month', 'day', 'hour', 'minute', 'second']

logs:
  login:
    enabled: true
    message: '&8[&a+&8]&f %player%'
  switch:
    enabled: true
    message: '&8[&e●&8]&f %player%§7 switched §f%from%&7 &m--➔&f %to%'
  disconnect:
    enabled: true
    message: '&8[&c-&8]&f %player%'
  nomoreplayers:
    enabled: true
    message: 'There are no more players online'

webhook:
  # Is used when you leave the default url or you were "none"
  default-url: 'https://discord.com/api/webhooks/****/****'
  
  login:
    enabled: false
    url: 'https://discord.com/api/webhooks/****/****'
    show-ip: false
  switch:
    enabled: false
    url: 'https://discord.com/api/webhooks/****/****'
  disconnect:
    enabled: false
    url: 'https://discord.com/api/webhooks/****/****'
  nomoreplayers:
    enabled: false
    url: 'https://discord.com/api/webhooks/****/****'
    content: 'There are no more players online'


save-connexion:
  enabled: false
  reason: 'server closed'
  list:
  - lobby
  - lobby01
  - lobby02
  message:
  - '&7&m---------------------------------------------'
  - '&cThe server you were on is now closed or restarting.'
  - '&cSo you have been teleported to the Lobby.'
  - '&7&m---------------------------------------------'
  
  # Kick message (if there is no Lobby available or present on a Lobby)
  kick-message:
  - '&7&m---------------------------------------------'
  - ''
  - '&cThe server you were on is now closed'
  - ''
  - '&6No Lobby available for the connection'
  - ''
  - '&ePlease try again later'
  - ''
  - '&7&m---------------------------------------------'


monitor:
  enabled: true
  interval: 120 #seconds
  
  #The server must be detected x times offline before being notified (to avoid simple restarts)
  detected-offline: 2
  
  # If this option is enabled, server-list does not need to be completed
  check-all-servers: true
  server-list:
  - lobby01
  - lobby02
  - lobby03
  - practice
  - bedwars
  
  notify:
    #permission: deltamanager.monitor.alerts
    
    show-seconds: false
    no-seconds: 'less than one minute'
    
    on-join:
      enabled: true
      message: '&2&l[&a&lDeltaManager&2&l]&c Offline servers :%servers%'
      servers: "\n&c- &4%server%&c since %duration%"
    
    offline:
      log:
        enabled: true
        log: '&4%server%&c server is now offline'
      staff-message: '&2&l[&a&lDeltaManager&2&l]&4 %server%&c server is now offline'
      webhook:
        enabled: false
        url: 'https://discord.com/api/webhooks/****/****'
        author: 'Server monitoring'
        authoricon: 'https://deltamc.fr/storage/img/server.png'
        title: '**%server%** server is now offline'
    
    back-online:
      log:
        enabled: true
        log: '&2%server%&a server is back online after %duration%'
      staff-message: '&2&l[&a&lDeltaManager&2&l]&2 %server%&a server is back online after %duration%'
      webhook:
        enabled: false
        url: 'https://discord.com/api/webhooks/****/****'
        author: 'Server monitoring'
        authoricon: 'https://deltamc.fr/storage/img/server.png'
        title: '**%server%** server is back online after **%duration%**'
